/******************************************************************************
*    Dis Programming Language 
*    disc - Bootstrap Dis Compiler
*
*    disc is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    disc is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with disc.  If not, see <http://www.gnu.org/licenses/>.
*
******************************************************************************/
module dlf.sem.Semantic;

import dlf.ast.Node;
import dlf.ast.Visitor;
import dlf.ast.Declaration;
import dlf.ast.Statement;
import dlf.ast.Expression;
import dlf.ast.Annotation;
import dlf.ast.Type;
import dlf.ast.SymbolTable;
import dlf.ast.Transform;

import std.stdio;

/**
* Semantic Pass for AST
*/
class Semantic : Visitor
{
    /// Current Symbol Table
    private SymbolTable mSymTable;

    //rules
    //semantic passes?

    //Type stack name -> Type 
    //Stack!(Type[char[]])

    /**
    * Run semantic passes 
    * Parse Tree -> AST
    */
    public Node run(Node astNode)
    {
        //TODO Multiple Runs?
        return dispatch(astNode, this);
    }

    /**new CPackage()
    * Visit PackageDeclaration
    */
    void visit(PackageDeclaration pack)
    {
        Information("Semantic: PackageDcl");

        mSymTable = pack.SymTable;

        // Imports
        //add default runtime imports when not available
        mapDispatch(pack.Imports);

        // Variables
        mapDispatch(pack.Variables);

        // Functions
        mapDispatch(pack.Functions);

        //Classes
        mapDispatch(pack.Classes);

        pack.replace(pack);
    }

    /**
    * Import Declaration
    */
    void visit(ImportDeclaration impDecl)
    {
        // Info
        Information("Semantic: ImportDecl %s", impDecl.Name);

        //semantic check for available PackageDeclarations
        if(impDecl.Package !is null)
        {
            impDecl.Package = dispatchAuto(impDecl.Package);
        }
        else
            Error("\tImport %s has not been solved", impDecl.Name);



        //when a type resolved from import package
        //generate missing declarations? compiler task?
        //Import external types into actual PackageDeclaration 
        //Mark as external 
        //error when a import isn't resolved

        //Remove not required imports
    }

    /**
    * Class Semantic Check
    */
    void visit(ClassDeclaration cls)
    {
    }

    /**
    * Trait Semantic
    */
    void visit(TraitDeclaration td)
    {
    }

    /**
    * Visit FunctionDeclaration
    */
    void visit(FunctionDeclaration func)
    { 
        Information("Semantic FuncDcl %s", func.Name);

        //resolve return value
        if(func.FuncType.ReturnType is null || func.FuncType.ReturnType == OpaqueType.Instance)
        {
            func.FuncType.ReturnType = VoidType.Instance;
            
            //if has body look through all return statements

            Information("\t Resolved ReturnType is '%s'", func.FuncType.ReturnType.toString());
        }
        else
            Information("\t ReturnType is %s", func.FuncType.ReturnType.toString());

        //check if no Body then do through parameters 
        //Single Pairs are types
        //Generate FunctionType here?
        //from saved FunctionParameter Structure generated by Parser?
        //extend class functions with class param
        
        //go into Body
        if(func.Body !is null)
            func.Body = dispatchAuto(func.Body);

    }

     /**
    * Semantic Checks for Variables
    */
    void visit(VariableDeclaration var)
    {
        Information("Semantic: VarDecl %s", var.Name);

        //Do Semantic Analysis for Initializer Expression if available
        if(var.Initializer !is null)
            var.Initializer = dispatchAuto(var.Initializer);

        //Set Datatype for Variable
        if(var.VarDataType == OpaqueType.Instance)
        {
            if(var.Initializer !is null)
            {
                var.VarDataType = var.Initializer.ReturnType;
                Information("\tResolved var type: %s", var.VarDataType);
            }
        }

        //DataType of Variable and Initializer must match
        if(var.Initializer !is null)
        {   
            //check for allowed conversions?
            // implicit casts check
            Information("\tVarType: %s, InitType: %s", var.VarDataType,var.Initializer.ReturnType); 
            //assert(var.VarDataType == var.Initializer.ReturnType);
        }

    }

    /**
    * Visit Block Statement
    */
    void visit(BlockStatement block)
    {
        Information("Semantic: BlockStmt");

        mSymTable = block.SymTable;

        //analyze the declarations inside of blockstatement
        
        foreach(Declaration sym; block.SymTable)
            dispatch(sym, this);

        //check each statement
        mapDispatch(block.Statements);

    }

    /**
    * Visit Expression Statement
    */
    void visit(ExpressionStatement expr)
    {
        //visit Expression
        expr.Expr = dispatchAuto(expr.Expr);

    }

    /**
    * Visit ReturnStatement
    */
    void visit(ReturnStatement rs)
    {
        //check rs.Expr returntype must match parent return type
    }

    /**
    * Visit Function Call
    */
    void visit(CallExpression call)
    {
        //TODO class Function Calls
        Information("Semantic: FuncCall %s", call.Function.toString());

        //Create Function instances here
        
        //check for function
        //call.mFunction.NType() == NodeType.DotIdentifier
        //Look for parameter type matching
        auto fexpr = call.Function;
        
        //Expression to Function

        if(fexpr.Kind == NodeKind.DotIdentifier)
        {
            Information("\t Is DotIdentifier -> Try to resolve type");
            auto resolve = resolve(cast(DotIdentifier)fexpr);

            if(resolve !is null)
            {
                Information("\t Resolve type: %s", resolve);
                extend(call.Function, resolve);
            }
            //look foreach
            //get function declaration
        }

        //check if Function exist
    }

    /**
    * Semantic Pass for DotIdentifier
    */
    void visit(DotIdentifier di)
    {
        // resolve returntype 
        // add node DotIdentifier pointo to Extend
        // auto decl = resolve(DotIdentifier di)
        // -> assign(di, decl);
        // di.ReturnType = decl.Type
    }

    /**
    * Semantic Pass for Assign Expression
    */
    void visit(AssignExpression ae)
    {
        //look for Target must be a declared value?
        //look for type match
    }
    
    /**
    * Semantic Pass for BinaryExpression
    */
    void visit(BinaryExpression be)
    {
        //analyze left and right expression first
        be.Left = dispatchAuto(be.Left);
        be.Right = dispatchAuto(be.Right);
        
        //look for type match

        //rewrite Binary Expression for none math types
        //detect build in math types
        // a + b ->
        // a.opAdd(b);
    
        //calculate literal expressions directly

        //return resulting Expression
    }

    /**
    * Semantic Pass for Literal Expression
    */
    void visit(LiteralExpression le)
    {
        //look for string value?
        //verify string value?
        
    }

    /**
    * Get the Declaration of a DotIdentifier
    * e.g. "this.foo.bar.x" is a VariableDeclaration(int)
    */
    private Declaration resolve(DotIdentifier di)
    {
        //Symbol Table should not be null
        if(mSymTable is null)
        {
            Error("\t Resolve DotIdentifier: SymbolTable is null");
            return null;
        }

        //TODO Detect this at front

        auto elements = di.length;
        if(elements == 1)
        {
            //search up
            auto sym = mSymTable;

            do
            {
                if(sym.contains(cast(string)di[0]))
                    return sym[cast(string)di[0]];
            
                sym = sym.pop();
            }
            while(sym !is null)
        }
        else
        {
            //go up 
            //search down
        }
        

        return null;
    }

    /**
    * Auto Dispatch
    */
    private T dispatchAuto(T)(T e)
    {
        return cast(T)dispatch(e, this, true);
    }

    /**
    * Map Dispatch to Arrays
    */
    private void mapDispatch(T)(T[] elements)
    {
        for(int i=0; i < elements.length; i++)
        {
            elements[i] = dispatchAuto(elements[i]);
        }
    }

    /**
    * Semantic Information Log
    */
    private void Information(T...)(string s, T args)
    {
        //TODO Change to Events
        writefln(s, args);
    }

    /**
    * Semantic Error Log
    */
    private void Error(T...)(string s, T args)
    {
        //TODO Change to Events
        writefln(s, args);
    }
}